import { Spell } from 'src/types/Spell';

const spells: Spell[] = [
  {
    higher_level: [],
    index: 'hellish-rebuke',
    name: 'Hellish Rebuke',
    desc: [
      'You point your finger, and the creature that damaged you is momentarily surrounded by hellish flames. The creature must make a dexterity saving throw. It takes 2d10 fire damage on a failed save, or half as much damage on a successful one.',
    ],
    range: '60 feet',
    components: ['V', 'S'],
    ritual: false,
    duration: 'Instantaneous',
    concentration: false,
    casting_time: '1 reaction',
    level: 1,
    damage: {
      damage_type: {
        index: 'fire',
        name: 'Fire',
        url: '/api/damage-types/fire',
      },
      damage_at_slot_level: {
        '1': '2d10',
      },
    },
    dc: {
      dc_type: {
        index: 'dex',
        name: 'DEX',
        url: '/api/ability-scores/dex',
      },
      dc_success: 'half',
    },
    school: {
      index: 'evocation',
      name: 'Evocation',
      url: '/api/magic-schools/evocation',
    },
    classes: [
      {
        index: 'warlock',
        name: 'Warlock',
        url: '/api/classes/warlock',
      },
    ],
    subclasses: [],
    url: '/api/spells/hellish-rebuke',
  },
  {
    higher_level: [],
    index: 'pass-without-trace',
    name: 'Pass Without Trace',
    desc: [
      "A veil of shadows and silence radiates from you, masking you and your companions from detection. For the duration, each creature you choose within 30 feet of you (including you) has a +10 bonus to Dexterity (Stealth) checks and can't be tracked except by magical means. A creature that receives this bonus leaves behind no tracks or other traces of its passage.",
    ],
    range: 'Self',
    components: ['V', 'S', 'M'],
    material: 'Ashes from a burned leaf of mistletoe and a sprig of spruce.',
    ritual: false,
    duration: 'Up to 1 hour',
    concentration: true,
    casting_time: '1 action',
    level: 2,
    school: {
      index: 'abjuration',
      name: 'Abjuration',
      url: '/api/magic-schools/abjuration',
    },
    classes: [
      {
        index: 'druid',
        name: 'Druid',
        url: '/api/classes/druid',
      },
      {
        index: 'ranger',
        name: 'Ranger',
        url: '/api/classes/ranger',
      },
    ],
    subclasses: [
      {
        index: 'lore',
        name: 'Lore',
        url: '/api/subclasses/lore',
      },
      {
        index: 'land',
        name: 'Land',
        url: '/api/subclasses/land',
      },
    ],
    url: '/api/spells/pass-without-trace',
  },
  {
    index: 'animate-dead',
    name: 'Animate Dead',
    desc: [
      "This spell creates an undead servant. Choose a pile of bones or a corpse of a Medium or Small humanoid within range. Your spell imbues the target with a foul mimicry of life, raising it as an undead creature. The target becomes a skeleton if you chose bones or a zombie if you chose a corpse (the GM has the creature's game statistics).",
      'On each of your turns, you can use a bonus action to mentally command any creature you made with this spell if the creature is within 60 feet of you (if you control multiple creatures, you can command any or all of them at the same time, issuing the same command to each one). You decide what action the creature will take and where it will move during its next turn, or you can issue a general command, such as to guard a particular chamber or corridor. If you issue no commands, the creature only defends itself against hostile creatures. Once given an order, the creature continues to follow it until its task is complete.',
      "The creature is under your control for 24 hours, after which it stops obeying any command you've given it. To maintain control of the creature for another 24 hours, you must cast this spell on the creature again before the current 24-hour period ends. This use of the spell reasserts your control over up to four creatures you have animated with this spell, rather than animating a new one.",
    ],
    higher_level: [
      'When you cast this spell using a spell slot of 4th level or higher, you animate or reassert control over two additional undead creatures for each slot level above 3rd. Each of the creatures must come from a different corpse or pile of bones.',
    ],
    range: '10 feet',
    components: ['V', 'S', 'M'],
    material: 'A drop of blood, a piece of flesh, and a pinch of bone dust.',
    ritual: false,
    duration: 'Instantaneous',
    concentration: false,
    casting_time: '1 minute',
    level: 3,
    school: {
      index: 'necromancy',
      name: 'Necromancy',
      url: '/api/magic-schools/necromancy',
    },
    classes: [
      {
        index: 'cleric',
        name: 'Cleric',
        url: '/api/classes/cleric',
      },
      {
        index: 'wizard',
        name: 'Wizard',
        url: '/api/classes/wizard',
      },
    ],
    subclasses: [
      {
        index: 'lore',
        name: 'Lore',
        url: '/api/subclasses/lore',
      },
    ],
    url: '/api/spells/animate-dead',
  },
  {
    higher_level: [],
    index: 'augury',
    name: 'Augury',
    desc: [
      'By casting gem-inlaid sticks, rolling dragon bones, laying out ornate cards, or employing some other divining tool, you receive an omen from an otherworldly entity about the results of a specific course of action that you plan to take within the next 30 minutes. The GM chooses from the following possible omens:',
      '- Weal, for good results',
      '- Woe, for bad results',
      '- Weal and woe, for both good and bad results',
      "- Nothing, for results that aren't especially good or bad",
      "The spell doesn't take into account any possible circumstances that might change the outcome, such as the casting of additional spells or the loss or gain of a companion.",
      'If you cast the spell two or more times before completing your next long rest, there is a cumulative 25 percent chance for each casting after the first that you get a random reading. The GM makes this roll in secret.',
    ],
    range: 'Self',
    components: ['V', 'S', 'M'],
    material:
      'Specially marked sticks, bones, or similar tokens worth at least 25gp.',
    ritual: true,
    duration: 'Instantaneous',
    concentration: false,
    casting_time: '1 minute',
    level: 2,
    school: {
      index: 'divination',
      name: 'Divination',
      url: '/api/magic-schools/divination',
    },
    classes: [
      {
        index: 'cleric',
        name: 'Cleric',
        url: '/api/classes/cleric',
      },
    ],
    subclasses: [
      {
        index: 'lore',
        name: 'Lore',
        url: '/api/subclasses/lore',
      },
    ],
    url: '/api/spells/augury',
  },
  {
    higher_level: [],
    index: 'mage-armor',
    name: 'Mage Armor',
    desc: [
      "You touch a willing creature who isn't wearing armor, and a protective magical force surrounds it until the spell ends. The target's base AC becomes 13 + its Dexterity modifier. The spell ends if the target dons armor or if you dismiss the spell as an action.",
    ],
    range: 'Touch',
    components: ['V', 'S', 'M'],
    material: 'A piece of cured leather.',
    ritual: false,
    duration: '8 hours',
    concentration: false,
    casting_time: '1 action',
    level: 1,
    school: {
      index: 'abjuration',
      name: 'Abjuration',
      url: '/api/magic-schools/abjuration',
    },
    classes: [
      {
        index: 'sorcerer',
        name: 'Sorcerer',
        url: '/api/classes/sorcerer',
      },
      {
        index: 'wizard',
        name: 'Wizard',
        url: '/api/classes/wizard',
      },
    ],
    subclasses: [
      {
        index: 'lore',
        name: 'Lore',
        url: '/api/subclasses/lore',
      },
    ],
    url: '/api/spells/mage-armor',
  },
  {
    higher_level: [],
    index: 'slow',
    name: 'Slow',
    desc: [
      'You alter time around up to six creatures of your choice in a 40-foot cube within range. Each target must succeed on a wisdom saving throw or be affected by this spell for the duration.',
      "An affected target's speed is halved, it takes a -2 penalty to AC and dexterity saving throws, and it can't use reactions. On its turn, it can use either an action or a bonus action, not both. Regardless of the creature's abilities or magic items, it can't make more than one melee or ranged attack during its turn.",
      "If the creature attempts to cast a spell with a casting time of 1 action, roll a d20. On an 11 or higher, the spell doesn't take effect until the creature's next turn, and the creature must use its action on that turn to complete the spell. If it can't, the spell is wasted.",
      'A creature affected by this spell makes another wisdom saving throw at the end of its turn. On a successful save, the effect ends for it.',
    ],
    range: '120 feet',
    components: ['V', 'S', 'M'],
    material: 'A drop of molasses.',
    ritual: false,
    duration: 'Up to 1 minute',
    concentration: true,
    casting_time: '1 action',
    level: 3,
    dc: {
      dc_type: {
        index: 'wis',
        name: 'WIS',
        url: '/api/ability-scores/wis',
      },
      dc_success: 'none',
      desc: 'On failed save, the creature is slowed.',
    },
    area_of_effect: {
      type: 'cube',
      size: 40,
    },
    school: {
      index: 'transmutation',
      name: 'Transmutation',
      url: '/api/magic-schools/transmutation',
    },
    classes: [
      {
        index: 'sorcerer',
        name: 'Sorcerer',
        url: '/api/classes/sorcerer',
      },
      {
        index: 'wizard',
        name: 'Wizard',
        url: '/api/classes/wizard',
      },
    ],
    subclasses: [
      {
        index: 'lore',
        name: 'Lore',
        url: '/api/subclasses/lore',
      },
      {
        index: 'land',
        name: 'Land',
        url: '/api/subclasses/land',
      },
    ],
    url: '/api/spells/slow',
  },
  {
    index: 'banishment',
    name: 'Banishment',
    desc: [
      'You attempt to send one creature that you can see within range to another plane of existence. The target must succeed on a charisma saving throw or be banished.',
      "If the target is native to the plane of existence you're on, you banish the target to a harmless demiplane. While there, the target is incapacitated. The target remains there until the spell ends, at which point the target reappears in the space it left or in the nearest unoccupied space if that space is occupied.",
      "If the target is native to a different plane of existence than the one you're on, the target is banished with a faint popping noise, returning to its home plane. If the spell ends before 1 minute has passed, the target reappears in the space it left or in the nearest unoccupied space if that space is occupied. Otherwise, the target doesn't return.",
    ],
    higher_level: [
      'When you cast this spell using a spell slot of 5th level or higher, you can target one additional creature for each slot level above 4th.',
    ],
    range: '60 feet',
    components: ['V', 'S', 'M'],
    material: 'An item distasteful to the target.',
    ritual: false,
    duration: 'Up to 1 minute',
    concentration: true,
    casting_time: '1 action',
    level: 4,
    dc: {
      dc_type: {
        index: 'cha',
        name: 'CHA',
        url: '/api/ability-scores/cha',
      },
      dc_success: 'none',
    },
    school: {
      index: 'abjuration',
      name: 'Abjuration',
      url: '/api/magic-schools/abjuration',
    },
    classes: [
      {
        index: 'cleric',
        name: 'Cleric',
        url: '/api/classes/cleric',
      },
      {
        index: 'paladin',
        name: 'Paladin',
        url: '/api/classes/paladin',
      },
      {
        index: 'sorcerer',
        name: 'Sorcerer',
        url: '/api/classes/sorcerer',
      },
      {
        index: 'warlock',
        name: 'Warlock',
        url: '/api/classes/warlock',
      },
      {
        index: 'wizard',
        name: 'Wizard',
        url: '/api/classes/wizard',
      },
    ],
    subclasses: [],
    url: '/api/spells/banishment',
  },
  {
    higher_level: [],
    index: 'stoneskin',
    name: 'Stoneskin',
    desc: [
      'This spell turns the flesh of a willing creature you touch as hard as stone. Until the spell ends, the target has resistance to nonmagical bludgeoning, piercing, and slashing damage.',
    ],
    range: 'Touch',
    components: ['V', 'S', 'M'],
    material: 'Diamond dust worth 100 gp, which the spell consumes.',
    ritual: false,
    duration: 'Up to 1 hour',
    concentration: true,
    casting_time: '1 action',
    level: 4,
    school: {
      index: 'abjuration',
      name: 'Abjuration',
      url: '/api/magic-schools/abjuration',
    },
    classes: [
      {
        index: 'druid',
        name: 'Druid',
        url: '/api/classes/druid',
      },
      {
        index: 'ranger',
        name: 'Ranger',
        url: '/api/classes/ranger',
      },
      {
        index: 'sorcerer',
        name: 'Sorcerer',
        url: '/api/classes/sorcerer',
      },
      {
        index: 'wizard',
        name: 'Wizard',
        url: '/api/classes/wizard',
      },
    ],
    subclasses: [
      {
        index: 'land',
        name: 'Land',
        url: '/api/subclasses/land',
      },
    ],
    url: '/api/spells/stoneskin',
  },
  {
    higher_level: [],
    index: 'chill-touch',
    name: 'Chill Touch',
    desc: [
      "You create a ghostly, skeletal hand in the space of a creature within range. Make a ranged spell attack against the creature to assail it with the chill of the grave. On a hit, the target takes 1d8 necrotic damage, and it can't regain hit points until the start of your next turn. Until then, the hand clings to the target.",
      'If you hit an undead target, it also has disadvantage on attack rolls against you until the end of your next turn.',
      "This spell's damage increases by 1d8 when you reach 5th level (2d8), 11th level (3d8), and 17th level (4d8).",
    ],
    range: '120 feet',
    components: ['V', 'S'],
    ritual: false,
    duration: '1 round',
    concentration: false,
    casting_time: '1 action',
    level: 0,
    attack_type: 'ranged',
    damage: {
      damage_type: {
        index: 'necrotic',
        name: 'Necrotic',
        url: '/api/damage-types/necrotic',
      },
      damage_at_character_level: {
        '1': '1d8',
        '5': '2d8',
        '11': '3d8',
        '17': '4d8',
      },
    },
    school: {
      index: 'necromancy',
      name: 'Necromancy',
      url: '/api/magic-schools/necromancy',
    },
    classes: [
      {
        index: 'sorcerer',
        name: 'Sorcerer',
        url: '/api/classes/sorcerer',
      },
      {
        index: 'warlock',
        name: 'Warlock',
        url: '/api/classes/warlock',
      },
      {
        index: 'wizard',
        name: 'Wizard',
        url: '/api/classes/wizard',
      },
    ],
    subclasses: [
      {
        index: 'lore',
        name: 'Lore',
        url: '/api/subclasses/lore',
      },
    ],
    url: '/api/spells/chill-touch',
  },
  {
    higher_level: [],
    index: 'beacon-of-hope',
    name: 'Beacon of Hope',
    desc: [
      'This spell bestows hope and vitality. Choose any number of creatures within range. For the duration, each target has advantage on wisdom saving throws and death saving throws, and regains the maximum number of hit points possible from any healing.',
    ],
    range: '30 feet',
    components: ['V', 'S'],
    ritual: false,
    duration: 'Up to 1 minute',
    concentration: true,
    casting_time: '1 action',
    level: 3,
    school: {
      index: 'abjuration',
      name: 'Abjuration',
      url: '/api/magic-schools/abjuration',
    },
    classes: [
      {
        index: 'cleric',
        name: 'Cleric',
        url: '/api/classes/cleric',
      },
    ],
    subclasses: [
      {
        index: 'lore',
        name: 'Lore',
        url: '/api/subclasses/lore',
      },
      {
        index: 'life',
        name: 'Life',
        url: '/api/subclasses/life',
      },
      {
        index: 'devotion',
        name: 'Devotion',
        url: '/api/subclasses/devotion',
      },
    ],
    url: '/api/spells/beacon-of-hope',
  },
  {
    index: 'inflict-wounds',
    name: 'Inflict Wounds',
    desc: [
      'Make a melee spell attack against a creature you can reach. On a hit, the target takes 3d10 necrotic damage.',
    ],
    higher_level: [
      'When you cast this spell using a spell slot of 2nd level or higher, the damage increases by 1d10 for each slot level above 1st.',
    ],
    range: 'Touch',
    components: ['V', 'S'],
    ritual: false,
    duration: 'Instantaneous',
    concentration: false,
    casting_time: '1 action',
    level: 1,
    attack_type: 'melee',
    damage: {
      damage_type: {
        index: 'necrotic',
        name: 'Necrotic',
        url: '/api/damage-types/necrotic',
      },
      damage_at_slot_level: {
        '1': '3d10',
        '2': '4d10',
        '3': '5d10',
        '4': '6d10',
        '5': '7d10',
        '6': '8d10',
        '7': '9d10',
        '8': '10d10',
        '9': '11d10',
      },
    },
    school: {
      index: 'necromancy',
      name: 'Necromancy',
      url: '/api/magic-schools/necromancy',
    },
    classes: [
      {
        index: 'cleric',
        name: 'Cleric',
        url: '/api/classes/cleric',
      },
    ],
    subclasses: [
      {
        index: 'lore',
        name: 'Lore',
        url: '/api/subclasses/lore',
      },
    ],
    url: '/api/spells/inflict-wounds',
  },
  {
    index: 'fireball',
    name: 'Fireball',
    desc: [
      'A bright streak flashes from your pointing finger to a point you choose within range and then blossoms with a low roar into an explosion of flame. Each creature in a 20-foot-radius sphere centered on that point must make a dexterity saving throw. A target takes 8d6 fire damage on a failed save, or half as much damage on a successful one.',
      "The fire spreads around corners. It ignites flammable objects in the area that aren't being worn or carried.",
    ],
    higher_level: [
      'When you cast this spell using a spell slot of 4th level or higher, the damage increases by 1d6 for each slot level above 3rd.',
    ],
    range: '150 feet',
    components: ['V', 'S', 'M'],
    material: 'A tiny ball of bat guano and sulfur.',
    ritual: false,
    duration: 'Instantaneous',
    concentration: false,
    casting_time: '1 action',
    level: 3,
    damage: {
      damage_type: {
        index: 'fire',
        name: 'Fire',
        url: '/api/damage-types/fire',
      },
      damage_at_slot_level: {
        '3': '8d6',
        '4': '9d6',
        '5': '10d6',
        '6': '11d6',
        '7': '12d6',
        '8': '13d6',
        '9': '14d6',
      },
    },
    dc: {
      dc_type: {
        index: 'dex',
        name: 'DEX',
        url: '/api/ability-scores/dex',
      },
      dc_success: 'half',
    },
    area_of_effect: {
      type: 'sphere',
      size: 20,
    },
    school: {
      index: 'evocation',
      name: 'Evocation',
      url: '/api/magic-schools/evocation',
    },
    classes: [
      {
        index: 'sorcerer',
        name: 'Sorcerer',
        url: '/api/classes/sorcerer',
      },
      {
        index: 'wizard',
        name: 'Wizard',
        url: '/api/classes/wizard',
      },
    ],
    subclasses: [
      {
        index: 'lore',
        name: 'Lore',
        url: '/api/subclasses/lore',
      },
      {
        index: 'fiend',
        name: 'Fiend',
        url: '/api/subclasses/fiend',
      },
    ],
    url: '/api/spells/fireball',
  },
  {
    higher_level: [],
    index: 'feather-fall',
    name: 'Feather Fall',
    desc: [
      "Choose up to five falling creatures within range. A falling creature's rate of descent slows to 60 feet per round until the spell ends. If the creature lands before the spell ends, it takes no falling damage and can land on its feet, and the spell ends for that creature.",
    ],
    range: '60 feet',
    components: ['V', 'M'],
    material: 'A small feather or a piece of down.',
    ritual: false,
    duration: '1 minute',
    concentration: false,
    casting_time: '1 reaction',
    level: 1,
    school: {
      index: 'transmutation',
      name: 'Transmutation',
      url: '/api/magic-schools/transmutation',
    },
    classes: [
      {
        index: 'bard',
        name: 'Bard',
        url: '/api/classes/bard',
      },
      {
        index: 'sorcerer',
        name: 'Sorcerer',
        url: '/api/classes/sorcerer',
      },
      {
        index: 'wizard',
        name: 'Wizard',
        url: '/api/classes/wizard',
      },
    ],
    subclasses: [
      {
        index: 'lore',
        name: 'Lore',
        url: '/api/subclasses/lore',
      },
    ],
    url: '/api/spells/feather-fall',
  },
  {
    higher_level: [],
    index: 'prismatic-wall',
    name: 'Prismatic Wall',
    desc: [
      'A shimmering, multicolored plane of light forms a vertical opaque wall--up to 90 feet long, 30 feet high, and 1 inch thick--centered on a point you can see within range. Alternatively, you can shape the wall into a sphere up to 30 feet in diameter centered on a point you choose within range. The wall remains in place for the duration. If you position the wall so that it passes through a space occupied by a creature, the spell fails, and your action and the spell slot are wasted.',
      'The wall sheds bright light out to a range of 100 feet and dim light for an additional 100 feet. You and creatures you designate at the time you cast the spell can pass through and remain near the wall without harm. If another creature that can see the wall moves to within 20 feet of it or starts its turn there, the creature must succeed on a constitution saving throw or become blinded for 1 minute.',
      "The wall consists of seven layers, each with a different color. When a creature attempts to reach into or pass through the wall, it does so one layer at a time through all the wall's layers. As it passes or reaches through each layer, the creature must make a dexterity saving throw or be affected by that layer's properties as described below.",
      'The wall can be destroyed, also one layer at a time, in order from red to violet, by means specific to each layer. Once a layer is destroyed, it remains so for the duration of the spell. A rod of cancellation destroys a prismatic wall, but an antimagic field has no effect on it.',
      "***1. Red.*** The creature takes 10d6 fire damage on a failed save, or half as much damage on a successful one. While this layer is in place, nonmagical ranged attacks can't pass through the wall. The layer can be destroyed by dealing at least 25 cold damage to it.",
      "***2. Orange.*** The creature takes 10d6 acid damage on a failed save, or half as much damage on a successful one. While this layer is in place, magical ranged attacks can't pass through the wall. The layer is destroyed by a strong wind.",
      '***3. Yellow.*** The creature takes 10d6 lightning damage on a failed save, or half as much damage on a successful one. This layer can be destroyed by dealing at least 60 force damage to it.',
      '***4. Green.*** The creature takes 10d6 poison damage on a failed save, or half as much damage on a successful one. A passwall spell, or another spell of equal or greater level that can open a portal on a solid surface, destroys this layer.',
      '***5. Blue.*** The creature takes 10d6 cold damage on a failed save, or half as much damage on a successful one. This layer can be destroyed by dealing at least 25 fire damage to it.',
      "***6. Indigo.*** On a failed save, the creature is restrained. It must then make a constitution saving throw at the end of each of its turns. If it successfully saves three times, the spell ends. If it fails its save three times, it permanently turns to stone and is subjected to the petrified condition. The successes and failures don't need to be consecutive; keep track of both until the creature collects three of a kind.",
      "While this layer is in place, spells can't be cast through the wall. The layer is destroyed by bright light shed by a daylight spell or a similar spell of equal or higher level.",
      "***7. Violet.*** On a failed save, the creature is blinded. It must then make a wisdom saving throw at the start of your next turn. A successful save ends the blindness. If it fails that save, the creature is transported to another plane of the GM's choosing and is no longer blinded. (Typically, a creature that is on a plane that isn't its home plane is banished home, while other creatures are usually cast into the Astral or Ethereal planes.) This layer is destroyed by a dispel magic spell or a similar spell of equal or higher level that can end spells and magical effects.",
    ],
    range: '60 feet',
    components: ['V', 'S'],
    ritual: false,
    duration: '10 minutes',
    concentration: false,
    casting_time: '1 action',
    level: 9,
    area_of_effect: {
      type: 'line',
      size: 90,
    },
    school: {
      index: 'abjuration',
      name: 'Abjuration',
      url: '/api/magic-schools/abjuration',
    },
    classes: [
      {
        index: 'wizard',
        name: 'Wizard',
        url: '/api/classes/wizard',
      },
    ],
    subclasses: [],
    url: '/api/spells/prismatic-wall',
  },
  {
    higher_level: [],
    index: 'power-word-kill',
    name: 'Power Word Kill',
    desc: [
      'You utter a word of power that can compel one creature you can see within range to die instantly. If the creature you choose has 100 hit points or fewer, it dies. Otherwise, the spell has no effect.',
    ],
    range: '60 feet',
    components: ['V'],
    ritual: false,
    duration: 'Instantaneous',
    concentration: false,
    casting_time: '1 action',
    level: 9,
    school: {
      index: 'enchantment',
      name: 'Enchantment',
      url: '/api/magic-schools/enchantment',
    },
    classes: [
      {
        index: 'bard',
        name: 'Bard',
        url: '/api/classes/bard',
      },
      {
        index: 'sorcerer',
        name: 'Sorcerer',
        url: '/api/classes/sorcerer',
      },
      {
        index: 'warlock',
        name: 'Warlock',
        url: '/api/classes/warlock',
      },
      {
        index: 'wizard',
        name: 'Wizard',
        url: '/api/classes/wizard',
      },
    ],
    subclasses: [],
    url: '/api/spells/power-word-kill',
  },
  {
    higher_level: [],
    index: 'telekinesis',
    name: 'Telekinesis',
    desc: [
      'You gain the ability to move or manipulate creatures or objects by thought. When you cast the spell, and as your action each round for the duration, you can exert your will on one creature or object that you can see within range, causing the appropriate effect below. You can affect the same target round after round, or choose a new one at any time. If you switch targets, the prior target is no longer affected by the spell.',
      "***Creature.*** You can try to move a Huge or smaller creature. Make an ability check with your spellcasting ability contested by the creature's Strength check. If you win the contest, you move the creature up to 30 feet in any direction, including upward but not beyond the range of this spell. Until the end of your next turn, the creature is restrained in your telekinetic grip. A creature lifted upward is suspended in mid-air.",
      'On subsequent rounds, you can use your action to attempt to maintain your telekinetic grip on the creature by repeating the contest.',
      "***Object.*** You can try to move an object that weighs up to 1,000 pounds. If the object isn't being worn or carried, you automatically move it up to 30 feet in any direction, but not beyond the range of this spell.",
      "If the object is worn or carried by a creature, you must make an ability check with your spellcasting ability contested by that creature's Strength check. If you succeed, you pull the object away from that creature and can move it up to 30 feet in any direction but not beyond the range of this spell.",
      'You can exert fine control on objects with your telekinetic grip, such as manipulating a simple tool, opening a door or a container, stowing or retrieving an item from an open container, or pouring the contents from a vial.',
    ],
    range: '60 feet',
    components: ['V', 'S'],
    ritual: false,
    duration: 'Up to 10 minutes',
    concentration: true,
    casting_time: '1 action',
    level: 5,
    area_of_effect: {
      type: 'sphere',
      size: 30,
    },
    school: {
      index: 'transmutation',
      name: 'Transmutation',
      url: '/api/magic-schools/transmutation',
    },
    classes: [
      {
        index: 'sorcerer',
        name: 'Sorcerer',
        url: '/api/classes/sorcerer',
      },
      {
        index: 'wizard',
        name: 'Wizard',
        url: '/api/classes/wizard',
      },
    ],
    subclasses: [],
    url: '/api/spells/telekinesis',
  },
  {
    higher_level: [],
    index: 'fear',
    name: 'Fear',
    desc: [
      "You project a phantasmal image of a creature's worst fears. Each creature in a 30-foot cone must succeed on a wisdom saving throw or drop whatever it is holding and become frightened for the duration.",
      "While frightened by this spell, a creature must take the Dash action and move away from you by the safest available route on each of its turns, unless there is nowhere to move. If the creature ends its turn in a location where it doesn't have line of sight to you, the creature can make a wisdom saving throw. On a successful save, the spell ends for that creature.",
    ],
    range: 'Self',
    components: ['V', 'S', 'M'],
    material: 'A white feather or the heart of a hen.',
    ritual: false,
    duration: 'Up to 1 minute',
    concentration: true,
    casting_time: '1 action',
    level: 3,
    dc: {
      dc_type: {
        index: 'wis',
        name: 'WIS',
        url: '/api/ability-scores/wis',
      },
      dc_success: 'none',
      desc: 'On fail, A creature drop whatever it is holding and become frightened for the duration.',
    },
    area_of_effect: {
      type: 'cone',
      size: 30,
    },
    school: {
      index: 'illusion',
      name: 'Illusion',
      url: '/api/magic-schools/illusion',
    },
    classes: [
      {
        index: 'bard',
        name: 'Bard',
        url: '/api/classes/bard',
      },
      {
        index: 'sorcerer',
        name: 'Sorcerer',
        url: '/api/classes/sorcerer',
      },
      {
        index: 'warlock',
        name: 'Warlock',
        url: '/api/classes/warlock',
      },
      {
        index: 'wizard',
        name: 'Wizard',
        url: '/api/classes/wizard',
      },
    ],
    subclasses: [
      {
        index: 'lore',
        name: 'Lore',
        url: '/api/subclasses/lore',
      },
    ],
    url: '/api/spells/fear',
  },
  {
    higher_level: [],
    index: 'prestidigitation',
    name: 'Prestidigitation',
    desc: [
      "This spell is a minor magical trick that novice spellcasters use for practice. You create one of the following magical effects within 'range':",
      'You create an instantaneous, harmless sensory effect, such as a shower of sparks, a puff of wind, faint musical notes, or an odd odor.',
      'You instantaneously light or snuff out a candle, a torch, or a small campfire.',
      'You instantaneously clean or soil an object no larger than 1 cubic foot.',
      'You chill, warm, or flavor up to 1 cubic foot of nonliving material for 1 hour.',
      'You make a color, a small mark, or a symbol appear on an object or a surface for 1 hour.',
      'You create a nonmagical trinket or an illusory image that can fit in your hand and that lasts until the end of your next turn.',
      'If you cast this spell multiple times, you can have up to three of its non-instantaneous effects active at a time, and you can dismiss such an effect as an action.',
    ],
    range: '10 feet',
    components: ['V', 'S'],
    ritual: false,
    duration: '1 hour',
    concentration: false,
    casting_time: '1 action',
    level: 0,
    school: {
      index: 'transmutation',
      name: 'Transmutation',
      url: '/api/magic-schools/transmutation',
    },
    classes: [
      {
        index: 'bard',
        name: 'Bard',
        url: '/api/classes/bard',
      },
      {
        index: 'sorcerer',
        name: 'Sorcerer',
        url: '/api/classes/sorcerer',
      },
      {
        index: 'warlock',
        name: 'Warlock',
        url: '/api/classes/warlock',
      },
      {
        index: 'wizard',
        name: 'Wizard',
        url: '/api/classes/wizard',
      },
    ],
    subclasses: [
      {
        index: 'lore',
        name: 'Lore',
        url: '/api/subclasses/lore',
      },
    ],
    url: '/api/spells/prestidigitation',
  },
  {
    higher_level: [],
    index: 'water-walk',
    name: 'Water Walk',
    desc: [
      'This spell grants the ability to move across any liquid surface--such as water, acid, mud, snow, quicksand, or lava--as if it were harmless solid ground (creatures crossing molten lava can still take damage from the heat). Up to ten willing creatures you can see within range gain this ability for the duration.',
      'If you target a creature submerged in a liquid, the spell carries the target to the surface of the liquid at a rate of 60 feet per round.',
    ],
    range: '30 feet',
    components: ['V', 'S', 'M'],
    material: 'A piece of cork.',
    ritual: true,
    duration: '1 hour',
    concentration: false,
    casting_time: '1 action',
    level: 3,
    school: {
      index: 'transmutation',
      name: 'Transmutation',
      url: '/api/magic-schools/transmutation',
    },
    classes: [
      {
        index: 'cleric',
        name: 'Cleric',
        url: '/api/classes/cleric',
      },
      {
        index: 'druid',
        name: 'Druid',
        url: '/api/classes/druid',
      },
      {
        index: 'ranger',
        name: 'Ranger',
        url: '/api/classes/ranger',
      },
      {
        index: 'sorcerer',
        name: 'Sorcerer',
        url: '/api/classes/sorcerer',
      },
    ],
    subclasses: [
      {
        index: 'lore',
        name: 'Lore',
        url: '/api/subclasses/lore',
      },
      {
        index: 'land',
        name: 'Land',
        url: '/api/subclasses/land',
      },
    ],
    url: '/api/spells/water-walk',
  },
  {
    higher_level: [],
    index: 'thaumaturgy',
    name: 'Thaumaturgy',
    desc: [
      'You manifest a minor wonder, a sign of supernatural power, within range. You create one of the following magical effects within range.',
      '- Your voice booms up to three times as loud as normal for 1 minute.',
      '- You cause flames to flicker, brighten, dim, or change color for 1 minute.',
      '- You cause harmless tremors in the ground for 1 minute.',
      '- You create an instantaneous sound that originates from a point of your choice within range, such as a rumble of thunder, the cry of a raven, or ominous whispers.',
      '- You instantaneously cause an unlocked door or window to fly open or slam shut.',
      '- You alter the appearance of your eyes for 1 minute.',
      'If you cast this spell multiple times, you can have up to three of its 1-minute effects active at a time, and you can dismiss such an effect as an action.',
    ],
    range: '30 feet',
    components: ['V'],
    ritual: false,
    duration: '1 minute',
    concentration: false,
    casting_time: '1 action',
    level: 0,
    school: {
      index: 'transmutation',
      name: 'Transmutation',
      url: '/api/magic-schools/transmutation',
    },
    classes: [
      {
        index: 'cleric',
        name: 'Cleric',
        url: '/api/classes/cleric',
      },
    ],
    subclasses: [
      {
        index: 'lore',
        name: 'Lore',
        url: '/api/subclasses/lore',
      },
    ],
    url: '/api/spells/thaumaturgy',
  },
  {
    higher_level: [],
    index: 'spike-growth',
    name: 'Spike Growth',
    desc: [
      'The ground in a 20-foot radius centered on a point within range twists and sprouts hard spikes and thorns. The area becomes difficult terrain for the duration. When a creature moves into or within the area, it takes 2d4 piercing damage for every 5 feet it travels.',
      "The transformation of the ground is camouflaged to look natural. Any creature that can't see the area at the time the spell is cast can make a Wisdom (Perception) check against your spell save DC to recognize the terrain as hazardous before entering it.",
    ],
    range: '150 feet',
    components: ['V', 'S', 'M'],
    material:
      'Seven sharp thorns or seven small twigs, each sharpened to a point.',
    ritual: false,
    duration: 'Up to 10 minutes',
    concentration: true,
    casting_time: '1 action',
    level: 2,
    area_of_effect: {
      type: 'cylinder',
      size: 20,
    },
    school: {
      index: 'transmutation',
      name: 'Transmutation',
      url: '/api/magic-schools/transmutation',
    },
    classes: [
      {
        index: 'druid',
        name: 'Druid',
        url: '/api/classes/druid',
      },
      {
        index: 'ranger',
        name: 'Ranger',
        url: '/api/classes/ranger',
      },
    ],
    subclasses: [
      {
        index: 'lore',
        name: 'Lore',
        url: '/api/subclasses/lore',
      },
      {
        index: 'land',
        name: 'Land',
        url: '/api/subclasses/land',
      },
    ],
    url: '/api/spells/spike-growth',
  },
  {
    higher_level: [],
    index: 'shield',
    name: 'Shield',
    desc: [
      'An invisible barrier of magical force appears and protects you. Until the start of your next turn, you have a +5 bonus to AC, including against the triggering attack, and you take no damage from magic missile.',
    ],
    range: 'Self',
    components: ['V', 'S'],
    ritual: false,
    duration: '1 round',
    concentration: false,
    casting_time: '1 reaction',
    level: 1,
    school: {
      index: 'abjuration',
      name: 'Abjuration',
      url: '/api/magic-schools/abjuration',
    },
    classes: [
      {
        index: 'sorcerer',
        name: 'Sorcerer',
        url: '/api/classes/sorcerer',
      },
      {
        index: 'wizard',
        name: 'Wizard',
        url: '/api/classes/wizard',
      },
    ],
    subclasses: [
      {
        index: 'lore',
        name: 'Lore',
        url: '/api/subclasses/lore',
      },
    ],
    url: '/api/spells/shield',
  },
  {
    higher_level: [],
    index: 'shocking-grasp',
    name: 'Shocking Grasp',
    desc: [
      "Lightning springs from your hand to deliver a shock to a creature you try to touch. Make a melee spell attack against the target. You have advantage on the attack roll if the target is wearing armor made of metal. On a hit, the target takes 1d8 lightning damage, and it can't take reactions until the start of its next turn.",
      "The spell's damage increases by 1d8 when you reach 5th level (2d8), 11th level (3d8), and 17th level (4d8).",
    ],
    range: 'Touch',
    components: ['V', 'S'],
    ritual: false,
    duration: 'Instantaneous',
    concentration: false,
    casting_time: '1 action',
    level: 0,
    attack_type: 'melee',
    damage: {
      damage_type: {
        index: 'lightning',
        name: 'Lightning',
        url: '/api/damage-types/lightning',
      },
      damage_at_character_level: {
        '1': '1d8',
        '5': '2d8',
        '11': '3d8',
        '17': '4d8',
      },
    },
    school: {
      index: 'evocation',
      name: 'Evocation',
      url: '/api/magic-schools/evocation',
    },
    classes: [
      {
        index: 'sorcerer',
        name: 'Sorcerer',
        url: '/api/classes/sorcerer',
      },
      {
        index: 'wizard',
        name: 'Wizard',
        url: '/api/classes/wizard',
      },
    ],
    subclasses: [
      {
        index: 'lore',
        name: 'Lore',
        url: '/api/subclasses/lore',
      },
    ],
    url: '/api/spells/shocking-grasp',
  },
  {
    higher_level: [],
    index: 'poison-spray',
    name: 'Poison Spray',
    desc: [
      'You extend your hand toward a creature you can see within range and project a puff of noxious gas from your palm. The creature must succeed on a constitution saving throw or take 1d12 poison damage.',
      "This spell's damage increases by 1d12 when you reach 5th level (2d12), 11th level (3d12), and 17th level (4d12).",
    ],
    range: '10 feet',
    components: ['V', 'S'],
    ritual: false,
    duration: 'Instantaneous',
    concentration: false,
    casting_time: '1 action',
    level: 0,
    damage: {
      damage_type: {
        index: 'poison',
        name: 'Poison',
        url: '/api/damage-types/poison',
      },
      damage_at_character_level: {
        '1': '1d12',
        '5': '2d12',
        '11': '3d12',
        '17': '4d12',
      },
    },
    dc: {
      dc_type: {
        index: 'con',
        name: 'CON',
        url: '/api/ability-scores/con',
      },
      dc_success: 'none',
    },
    school: {
      index: 'conjuration',
      name: 'Conjuration',
      url: '/api/magic-schools/conjuration',
    },
    classes: [
      {
        index: 'sorcerer',
        name: 'Sorcerer',
        url: '/api/classes/sorcerer',
      },
      {
        index: 'warlock',
        name: 'Warlock',
        url: '/api/classes/warlock',
      },
      {
        index: 'wizard',
        name: 'Wizard',
        url: '/api/classes/wizard',
      },
    ],
    subclasses: [],
    url: '/api/spells/poison-spray',
  },
];
export default spells;
